project:
  type: website
  render: 
    - "*.qmd"
    - "!working/*"
    - "!working/archive/*"    
    - "01*"
    - "02*"
    - "03*"
    - "!04*"
    - "!05*"
    - "!06*"
    - "!07*"
  output-dir: ./wipdocs/

website:  
  title: "Latent Variable Modelling"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - 01_datawrangle.qmd
      - 02_dimension_reduction.qmd
      - 03_efa.qmd
      # - 04_cfa.qmd
      # - 06_reliability.qmd
      # - 06_sem.qmd
      - section: "Additional Docs"
        contents:
          - z_eigen.qmd
          # - z_lgc_lmm.qmd

format:
  html:
    toc: true
    toc_float: true
    link-citations: true
    theme: 
      - cosmo
      - assets/style-labs.scss
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


