<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4: Confirmatory Factor Analysis – Latent Variable Modelling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-af8acd9e0062ec246c222f4d4317722b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>

function toggle_visibility(id1, id2) {

var e = document.getElementById(id1);

var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('jk-circle-right')) {

    f.classList.add('jk-circle-down')

    f.classList.remove('jk-circle-right')

} else {

    f.classList.add('jk-circle-right')

    f.classList.remove('jk-circle-down')

}

}

</script>



<!---<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>-->

<link href="site_libs/panelset-0.3.0/panelset.css" rel="stylesheet">

<script src="site_libs/panelset-0.3.0/panelset.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04_cfa.html">4: Confirmatory Factor Analysis</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Latent Variable Modelling</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_datawrangle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1: Data Wrangling for Questionnaires</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_dimension_reduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2: Dimension Reduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_efa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3: Exploratory Factor Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_cfa.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">4: Confirmatory Factor Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
 <span class="menu-text">05_reliability.qmd</span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Additional Docs</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./z_eigen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">optional extra: eigen decomposition</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#cfa" id="toc-cfa" class="nav-link active" data-scroll-target="#cfa">CFA</a></li>
  <li><a href="#cfa-in-r---the-lavaan-package" id="toc-cfa-in-r---the-lavaan-package" class="nav-link" data-scroll-target="#cfa-in-r---the-lavaan-package">CFA in R - The lavaan package</a></li>
  <li><a href="#model-fit" id="toc-model-fit" class="nav-link" data-scroll-target="#model-fit">“Model Fit”</a>
  <ul class="collapse">
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom">Degrees of Freedom</a></li>
  <li><a href="#model-fit-measures" id="toc-model-fit-measures" class="nav-link" data-scroll-target="#model-fit-measures">Model Fit Measures</a></li>
  </ul></li>
  <li><a href="#latent-variable-scaling" id="toc-latent-variable-scaling" class="nav-link" data-scroll-target="#latent-variable-scaling">Latent Variable Scaling</a></li>
  <li><a href="#making-diagrams" id="toc-making-diagrams" class="nav-link" data-scroll-target="#making-diagrams">Making diagrams</a></li>
  <li><a href="#model-modifications" id="toc-model-modifications" class="nav-link" data-scroll-target="#model-modifications">Model modifications</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">4: Confirmatory Factor Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="lo">
<ul>
<li>Learn about a method of testing theoretical models of the construct(s) tha result in variability in a set of observed variables</li>
<li>First use of the <strong>{lavaan}</strong> package in R</li>
</ul>
</div>
<section id="cfa" class="level1">
<h1>CFA</h1>
<p>Confirmatory Factor Analysis (CFA) is a method that allows us to test a pre-specified factor structure (or to compare competing hypothesized structures). Typically these factor structures are ones that have been proposed based on theory or on previous research. Note that this is a change from the ‘exploratory’ nature of EFA to a situation in which we are explicitly imposing a theoretical model on the data.</p>
<p>The diagram for a Confirmatory Factor Analysis model looks very similar to that of an Exploratory Factor Analysis, but we now have the explicit <strong>absence</strong> of some arrows - i.e.&nbsp;a variable loads on to a specific factor (or factor<em>s</em> - we can have a variable that loads on multiple), and <strong>not</strong> on others.</p>
<p>The absence of some arrows is what imposes our theory here - the diagram in <a href="#fig-cfa" class="quarto-xref">Figure&nbsp;1</a> makes the claim that the <em>only</em> reason we would see a correlation between items <code>y1</code> and <code>y6</code> is because the underlying factors are correlated.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-cfa" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cfa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/diag_cfa.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cfa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: CFA as a diagram
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="cfa-in-r---the-lavaan-package" class="level1">
<h1>CFA in R - The lavaan package</h1>
<p>For these sort of models, we’re going to rely heavily on the <strong>lavaan</strong> (<strong>La</strong>tent <strong>Va</strong>riable <strong>An</strong>alysis) package. This is the main package in R for fitting a whole wealth of model types - all of which come under the umbrella term of “Structural Equation Models (SEM)”, and there is a huge scope of what we can do with it.</p>
<p><strong>Operators in lavaan</strong></p>
<p>The first thing to get to grips with is the various new operators which <strong>lavaan</strong> allows us to use.</p>
<p>Our standard multiple regression formula in R was specified as</p>
<pre><code>y ~ x1 + x2 + x3 + ...</code></pre>
<p>In lavaan, we continue to fit regressions using the <code>~</code> symbol, but we can also specify the construction of latent variables using <code>=~</code> and residual variances &amp; covariances using <code>~~</code>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Formula type</th>
<th style="text-align: right;">Operator</th>
<th style="text-align: right;">Mnemonic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">latent variable definition</td>
<td style="text-align: right;"><code>=~</code></td>
<td style="text-align: right;">“is measured by”</td>
</tr>
<tr class="even">
<td style="text-align: right;">regression</td>
<td style="text-align: right;"><code>~</code></td>
<td style="text-align: right;">“is regressed on”</td>
</tr>
<tr class="odd">
<td style="text-align: right;">(residual) (co)variance</td>
<td style="text-align: right;"><code>~~</code></td>
<td style="text-align: right;">“is correlated with”</td>
</tr>
<tr class="even">
<td style="text-align: right;">intercept</td>
<td style="text-align: right;"><code>~1</code></td>
<td style="text-align: right;">“has an intercept”</td>
</tr>
<tr class="odd">
<td style="text-align: right;">defined parameters</td>
<td style="text-align: right;"><code>:=</code></td>
<td style="text-align: right;">“is defined as”</td>
</tr>
</tbody>
</table>
<p>(from https://lavaan.ugent.be/tutorial/syntax1.html)</p>
<div class="rtip">
<p><strong>Fitting models with lavaan</strong></p>
<p>In practice, fitting models in <strong>lavaan</strong> tends to be a little different from things like <code>lm()</code> and <code>(g)lmer()</code>. Instead of including the model formula <em>inside</em> the fit function (e.g., <code>lm(y ~ x1 + x2, data = df)</code>), we tend to do it in a step-by-step process. This is because as our models become more complex, our formulas can get pretty long!</p>
<p>In <strong>lavaan</strong>, it is typical to write the model as a character string (e.g.&nbsp;<code>mymodel &lt;- "y ~ x1 + x2"</code>) and then we pass that formula along with the data to the relevant <strong>lavaan</strong> function such as <code>cfa()</code> or <code>sem()</code>, giving it the formula and the data: <code>cfa(mymodel, data = mydata)</code>.</p>
<p>So if we are fitting a model that — in a diagram — looks like this:</p>
<p><img src="images/cfa_example.png" class="img-fluid"></p>
<ol type="1">
<li>First we specify the model. By default, the correlation between factors will be included, but it’s good to specify it anyway</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mydata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/lv_sleepfocus.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>mymodel <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="st">  sleep =~ q_1 + q_2 + q_3</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="st">  focus =~ q_4 + q_5 + q_6</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="st">  sleep ~~ focus # included by default</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Estimate the model (other fitting functions include <code>sem()</code>, <code>growth()</code> and <code>lavaan()</code>):</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>myfittedmodel <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mymodel, <span class="at">data =</span> mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>Examine the fitted model:</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(myfittedmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output of the <code>summary()</code> will show you each estimated parameter in your model (you can think of these as each of the lines in the diagram). It groups these according to whether they are loadings onto latent variables (the factors), covariances, regressions, variances etc.</p>
<pre><code>...
... info about estimation process
...
... info about model identification and fit
...
Parameter Estimates:

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  sleep =~                                            
    q_1               1.000                           
    q_2               0.838    0.145    5.777    0.000
    q_3              -0.846    0.146   -5.780    0.000
  focus =~                                            
    q_4               1.000                           
    q_5              -0.706    0.103   -6.891    0.000
    q_6               0.843    0.123    6.866    0.000

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  sleep ~~                                            
    focus            -0.157    0.052   -3.011    0.003

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .q_1               0.834    0.107    7.772    0.000
   .q_2               1.045    0.094   11.132    0.000
   .q_3               1.111    0.098   11.362    0.000
   .q_4               1.100    0.131    8.400    0.000
   .q_5               0.985    0.084   11.738    0.000
   .q_6               1.031    0.103   10.042    0.000
    sleep             0.549    0.117    4.707    0.000
    focus             0.792    0.148    5.365    0.000
</code></pre>
</div>
</section>
<section id="model-fit" class="level1">
<h1>“Model Fit”</h1>
<p>You’ll have probably heard the term “model fit” many times when learning about statistics. However, the exact meaning of the phrase is different for different modelling frameworks.</p>
<p>We can think more generally as “model fit” as asking “how well does our model reproduce the characteristics of the data that we observed?”. In things like multiple regression, this has been tied to the question of “how much variance can we explain in outcome <span class="math inline">\(y\)</span> with our set of predictors?”<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p>For methods like CFA, we are working with models that are fitted to the <em>covariances matrix</em> rather than to an outcome variable, so “model fit” becomes “how well can our model reproduce our observed covariance matrix?”.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: how does a model reproduce a covariance matrix?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>After so much time working in a regression world, where we can think of each value on the outcome variable being predicted by some combination of the predictor variables, it can be a bit odd to think about how models like CFA and SEM predict the values in a covariance matrix. The missing link is probably easiest described by showing what different theoretical models <em>imply</em> for a covariance matrix.</p>
<p>For instance, in <a href="#fig-pt1" class="quarto-xref">Figure&nbsp;2</a>, we can see a (rather odd) theoretical model of four variables. Each variable has some variance (the looped arrows back on themselves), but the lack of arrows between them indicates that we would <em>expect</em> to see covariances of 0 between them all. If we then collect data on those four variables, and fit the model to that data, it will estimate the parameters in the model (<span class="math inline">\(u_{y1}\)</span> to <span class="math inline">\(u_{y4}\)</span>) based on an optimisation method such as maximum likelihood estimation. These parameters therefore imply a covariance matrix, and we can compare this to the actual covariance matrix we observe between the variables.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pt1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pt1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/intropathtrace/Slide1.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pt1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: A theoretical model that four variables are uncorrelated
</figcaption>
</figure>
</div>
</div>
</div>
<p>We could have another theoretical model of how the four variables are related. For instance, we could just say “they’re all related to each other for whatever reason!”. This would be essentially like connecting each pair of variables by a double-headed arrow (indicating covariance), as in <a href="#fig-pt2" class="quarto-xref">Figure&nbsp;3</a>.</p>
<p>This model means we estimate all those covariances between each pair of variables, and so we can <em>perfectly</em> reproduce any observed covariance matrix, but we’re not gaining anything. We started with 10 things in the covariance matrix, and the model has to estimate 10 things (letters <span class="math inline">\(a\)</span> to <span class="math inline">\(f\)</span> and <span class="math inline">\(u_{y1}\)</span> to <span class="math inline">\(u_{y4}\)</span> in <a href="#fig-pt2" class="quarto-xref">Figure&nbsp;3</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pt2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pt2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/intropathtrace/Slide2.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pt2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: A theoretical model that four variables are all correlated with one another
</figcaption>
</figure>
</div>
</div>
</div>
<p>Another way in which we could theorise about relations between the four variables is to posit that they are only related <strong>because</strong> they are each representing (to different degrees) the same underlying “latent factor” (i.e., the same construct). This is shown in <a href="#fig-pt3" class="quarto-xref">Figure&nbsp;4</a>, and only requires us to estimate 8 things, rather than 10. In doing so it also assumes the existence of some latent factor <span class="math inline">\(F\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pt3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pt3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/intropathtrace/Slide3.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pt3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: A theoretical model that four variables are related to one another <em>because</em> they are all manifest variables of some latent factor
</figcaption>
</figure>
</div>
</div>
</div>
<p>The core idea here is that from the diagram on the left there is an algorithmic way to calculate an implied value for the entries in the covariance matrix on the right. So from a given diagram, we can work out what values we would expect to see in a covariance matrix, in terms of combinations of estimated paths in the diagram.</p>
<p>Once the model gets fitted to some data and the paths are estimated, these paths give us an implied covariance matrix that we can evaluate against our observed one, therefore allowing us to talk about “model fit”</p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 48%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th>model fit in <code>lm()</code></th>
<th>model fit in CFA/SEM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“how well does our model reproduce the values in the outcome variable?”</td>
<td>“how well does our model reproduce the values in our covariance matrix?”</td>
</tr>
</tbody>
</table>
<section id="degrees-of-freedom" class="level2">
<h2 class="anchored" data-anchor-id="degrees-of-freedom">Degrees of Freedom</h2>
<p>In regression, we could only talk about model fit if we had more than 2 datapoints. This is because there is only one possible line that we can fit between 2 datapoints, and this line explains <em>all</em> of the variance in the outcome variable (it uses up all our 2 degrees of freedom to estimate the intercept and the slope).</p>
<p>The logic is the same for model fit in terms of CFA and SEM - we need more observed things than we have parameters that our model is estimating. The difference is that “observed things” are the values in our covariance matrix, rather than individual observations. The idea is that we need to be estimating fewer parameters (fewer “paths” or lines in the diagram) than there are unique values (variances and covariances) in our covariance matrix. This is because if we just fit paths between all our variables, then our model would be able to reproduce the data perfectly (just like a regression with 2 datapoints has an <span class="math inline">\(R^2\)</span> of 1).</p>
<p>The degrees of freedom for methods like CFA, Path Analysis and SEM, that are fitted to the covariance matrix of our data, correspond to the number of <em>knowns</em> (observed covariances/variances from our sample) minus the number of <em>unknowns</em> (parameters to be estimated by the model).</p>
<div class="sticky">
<p><strong>degrees of freedom = number of knowns - number of unknowns</strong></p>
<ul>
<li>number of knowns: how many unique variances/covariances in our data?<br>
The number of knowns in a covariance matrix of <span class="math inline">\(k\)</span> observed variables is equal to <span class="math inline">\(\frac{k \cdot (k+1)}{2}\)</span>.<br>
</li>
<li>number of unknowns: how many parameters is our model estimating?<br>
We can reduce the number of unknowns (thereby getting back a degree of freedom) by fixing parameters to be specific values. <em>By removing a path altogether, we are fixing it to be zero.</em></li>
</ul>
<p>A model is only able to be estimated if it has at least 0 degrees of freedom (if there are as many knowns as unknowns).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 45%">
<col style="width: 2%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>degrees of freedom</th>
<th>-</th>
<th>what can/can’t be done</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(&gt;0\)</span> degrees of freedom</td>
<td><strong>over-identified</strong></td>
<td>can estimate parameters and their standard errors, and can estimate model fit</td>
</tr>
<tr class="even">
<td>0 degrees of freedom</td>
<td><strong>just-identified</strong></td>
<td>can estimate parameters and their standard errors, but not model fit</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(&lt;0\)</span> degrees of freedom</td>
<td><strong>under-identified</strong></td>
<td>can estimate parameters but not their standard errors (so basically useless), and cannot estimate model fit</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="model-fit-measures" class="level2">
<h2 class="anchored" data-anchor-id="model-fit-measures">Model Fit Measures</h2>
<p>There are <em>loads</em> of different metrics that people use to examine model fit for CFA and SEM, and there’s lots of debate over the various merits and disadvantages as well as the proposed cut-offs to be used with each method.</p>
<p>The most fundamental test of model fit is a <span class="math inline">\(\chi^2\)</span> test, which reflects the discrepancy between our observed covariance matrix and the <em>model-implied</em> covariance matrix. If we denote the population covariance matrix as <span class="math inline">\(\Sigma\)</span> and the model-implied covariance matrix as <span class="math inline">\(\Sigma(\Theta)\)</span>, then we can think of the null hypothesis here as <span class="math inline">\(H_0: \Sigma - \Sigma(\Theta) = 0\)</span>. In this way our null hypothesis is that our theoretical model is correct (and can therefore perfectly reproduce the covariance matrix). This means that a significant result indicates <em>poor</em> fit. It is very sensitive to departures from normality, as well as sample size (for models with <span class="math inline">\(n&gt;400\)</span>, the <span class="math inline">\(\chi^2\)</span> is almost always significant), and can often lead to rejecting otherwise adequate models.</p>
<p>Alongside this, the main four fit indices that are commonly used are known as RMSEA, SRMR, CFI and TLI. Smaller values of RMSEA and SRMR mean better fit while larger values of CFI and TLI mean better fit.</p>
<p><strong>Convention:</strong> if <span class="math inline">\(\textrm{RMSEA} &lt; .05\)</span>, <span class="math inline">\(\textrm{SRMR} &lt; .05\)</span>, <span class="math inline">\(\textrm{TLI} &gt; .95\)</span> and <span class="math inline">\(\textrm{CFI} &gt; .95\)</span> then the model fits well.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: absolute fit indices
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fitmeas_abs.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: incremental fit indices
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fitmeas_inc.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="rtip">
<p><strong>Fit Indices in R</strong></p>
<p>In R, we can ask for more fit measures in a number of ways:</p>
<ol type="1">
<li><p>We can ask for them to be added to the <code>summary()</code> output by using <code>summary(myfittedmodel, fit.measures = TRUE)</code>. The output gets pretty long, so we won’t print it here.</p></li>
<li><p>We can use the <code>fitmeasures()</code> function, by just giving it our fitted model object: <code>fitmeasures(myfittedmodel)</code>. Even this gives us a lot of information - there are hundreds of different measures of “model fit” that people have developed, and it lists lots of them. Often, it is therefore easier to just index the specific ones we want:</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fitmeasures</span>(myfittedmodel)[<span class="fu">c</span>(<span class="st">"srmr"</span>,<span class="st">"rmsea"</span>,<span class="st">"cfi"</span>,<span class="st">"tli"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      srmr      rmsea        cfi        tli 
0.02837775 0.01903349 0.99516293 0.99093049 </code></pre>
</div>
</div>
</div>
<p>One initially slightly bizarre aspect of latent variable models is that they involve estimating parameters between variables <strong>some of which we never observe</strong>. This seems almost like magic - we ask people questions about how well they sleep, if they fidget or worry etc., and somehow we are able to then estimate parameters concerning some underlying latent variable that represents ‘anxiety’ (but that we could never even hope to measure). The existence of any such latent variable is extremely theory driven - we are making a strong claim that there <strong>is</strong> some underlying thing that is causing our observed variables to covary. In diagrams like <a href="#fig-cfa" class="quarto-xref">Figure&nbsp;1</a>, we never observe the latent variables <code>F1</code> or <code>F2</code>, we simply theorise them into existence<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> as an explanation for what we <em>do</em> observe.</p>
<p>One important point is that models with latent variables that exhibit “good fit” do not prove the existence of any latent variable (such a task is impossible). In fact, it’s entirely possible that there are other theoretical models that fit equally well but without positing the existence of latent variables. Conceptually, we should always be scrutinising the meaning of our latent variables in the context of what we know (or think) about the field in which we are working.</p>
</section>
</section>
<section id="latent-variable-scaling" class="level1">
<h1>Latent Variable Scaling</h1>
<p>If we are happy to commit to the latent variables in our model being <em>conceptually meaningful</em>, we still need to define these variables <em>numerically</em>.</p>
<p>Think of a factor model as containing sets of regressions of <span class="math inline">\(item1 = \lambda_1\cdot Factor + u_1\)</span>, but where we never observe the “Factor” variable. So how can we ever estimate this model? In order to estimate parameters of these models (parameters like <span class="math inline">\(\lambda_1\)</span> - the factor loadings), we must commit to fixing some numeric feature of our latent variable - we must somehow fix its scale.</p>
<p>In <a href="#fig-df1" class="quarto-xref">Figure&nbsp;5</a>, we can see a model of a latent factor loading on to 4 items. The number of paths in the model (all the arrows) is greater than the number of known values in our covariance matrix. However, we get around this by <em>fixing certain parameters to be specific values</em>. For instance, we fix the paths from the residuals to the items to be 1 residual factor loadings to be 1 (this is almost always done, and means that often the diagrams are drawn more simply with the residuals presented as curved arrows from the items instead, but it’s the same model). While this makes our model over-identified (10 observed things, 9 things to estimate), there are infinitely many sets of numbers that would fit here because the latent factor has no numeric scale. We need to provide the number line on which we are going to score it.</p>
<p>To get our heads around this, imagine a simple regression model <code>lm(shoe_size ~ height)</code>. The variable <code>height</code> could be measured in mm, cm, m, km, inches, feet, etc., and all would be exactly the same model, but each using a different set of numbers. The idea here is (conceptually) the same - we need to numerically define what 0-1 maps to for our latent variable.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-df1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-df1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/lv_scaling/Slide1.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-df1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: A four item factor structure. Fixing the four residual factor loadings to be 1 makes the model identifiable (10 knowns, and 9 parameters to estimate), but the latent variable has no scale
</figcaption>
</figure>
</div>
</div>
</div>
<p>There are two ways to typically provide a latent variable with a scale. The first is to fix one of the factor loadings to be 1. This means the latent variable inherits the scale of that item (<a href="#fig-df2" class="quarto-xref">Figure&nbsp;6</a>). The second approach fixes the variance of the latent variable to be 1 (<a href="#fig-df3" class="quarto-xref">Figure&nbsp;7</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-df2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-df2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/lv_scaling/Slide2.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-df2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: A four item factor structure, fitted with the ‘marker method’
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-df3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-df3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/lv_scaling/Slide3.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-df3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: A four item factor structure. With the latent variable variance fixed to 1 (i.e., standardised)
</figcaption>
</figure>
</div>
</div>
</div>
<div class="sticky">
<p><strong>Scaling a latent variable</strong></p>
<ul>
<li>“marker method”: fix the first factor loading to 1. Useful if you have one specific item that is conceptually stronger than others and measured on a meaningful scale</li>
<li>“unit variance”: fix the variance of the latent variable to 1. Useful to evaluate factor loadings as these will represent standardised contribution of factor on each item.</li>
</ul>
</div>
<div class="rtip">
<p><strong>Latent Variable Scaling in R</strong></p>
<p>In <strong>lavaan</strong>, using <code>cfa()</code> will default to using the “marker method” and fixing the first loading of each factor to equal 1.</p>
<p>While the two models below are essentially the same, we can switch up <em>which</em> specific item we want to have the loading fixed for, and just put that one first when defining the factor (e.g., note below that the order of items differs when defining the <code>sleep</code> factor).</p>
<div class="columns">
<div class="column" style="width:48%;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mymodel <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="st">  sleep =~ q_1 + q_2 + q_3</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="st">  focus =~ q_4 + q_5 + q_6</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="st">  sleep ~~ focus # included by default</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cfa</span>(mymodel, <span class="at">data =</span> mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:48%;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mymodel <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="st">  sleep =~ q_3 + q_1 + q_2</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="st">  focus =~ q_4 + q_5 + q_6</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="st">  sleep ~~ focus # included by default</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cfa</span>(mymodel, <span class="at">data =</span> mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>If instead we want to scale the latent variables by fixing their variances to be equal to 1, then we can use <code>std.lv = TRUE</code> when fitting the model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>myfittedmodel <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mymodel, <span class="at">data =</span> mydata)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>myfittedmodel_std <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mymodel, <span class="at">data =</span> mydata, <span class="at">std.lv =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There’s a lot of parameter estimates in these sorts of models, so it looks like a lot differs between these models. But remember the models themselves are the same, we’re just re-scaling the latent variable, and so re-scaling the estimates.</p>
<p>In the two sets of loadings below, there is a link — the ratios are the same! If we take the set on the right hand side, but re-express them relative to the first one (the loading of 0.741), then we get back those loadings on the left hand side! $ = $0.838 and $ = $-0.846.</p>
<p>There is one key difference here - the hypothesis testing stuff (the <code>Std.Err</code>, <code>z-value</code> and <code>P(&gt;|z|)</code> columns) will be different because they are taking each estimate and testing against the null hypothesis that the estimate is zero.</p>
<div class="columns">
<div class="column" style="width:48%;">
<p><strong>first loading = 1</strong></p>
<pre><code>Latent Variables:
            Estimate  Std.Err  z-value  P(&gt;|z|)
  sleep =~  
    q_1     1.000                           
    q_2     0.838     0.145    5.777    0.000
    q_3    -0.846     0.146   -5.780    0.000</code></pre>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:48%;">
<p><strong>latent variable variance = 1</strong></p>
<pre><code>Latent Variables:
            Estimate  Std.Err  z-value  P(&gt;|z|)
  sleep =~                                            
    q_1     0.741     0.079    9.415    0.000
    q_2     0.621     0.073    8.485    0.000
    q_3    -0.627     0.075   -8.403    0.000</code></pre>
</div>
</div>
<p><strong>Post-hoc standardisation</strong></p>
<p>We can also quickly get out standardised estimates (or ‘standardized’ if you’re a north american speaker!) by simply asking for them in the <code>summary()</code>. This will output extra columns next to the parameter estimates.</p>
<ul>
<li>The <code>std.lv</code> column shows the estimates if the latent variables have a variance equal to 1 (“std.lv” = “standardised latent variables”).<br>
</li>
<li>The <code>std.all</code> column shows us the estimates if the latent variables a variance equal to 1 <strong>and</strong> the observed variables have variances equal to 1 (“std.all” = “all things standardised”).</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(myfittedmodel, <span class="at">standardized =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>Latent Variables:
            Estimate  Std.Err  z-value  P(&gt;|z|)  Std.lv  Std.all
  sleep =~    
    q_1     1.000                                0.741    0.630
    q_2     0.838     0.145    5.777    0.000    0.621    0.519
    q_3    -0.846     0.146   -5.780    0.000   -0.627   -0.511</code></pre>
</div>
</section>
<section id="making-diagrams" class="level1">
<h1>Making diagrams</h1>
<p>For more complex models with latent variables, we will almost always have to make diagrams manually, either in generic presentation software such as powerpoint or google slides, or in specific software such as <a href="https://semdiag.psychstat.org/" target="_blank">semdiag</a>.</p>
<p>R has a couple of packages which work well enough for some of the more common model structures such as CFA.</p>
<p>The <code>semPaths()</code> function from <strong>semPlot</strong> package can take a fitted lavaan model and create a nice diagram.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(myfittedmodel, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">what =</span> ?, <span class="co"># line thickness &amp; color by... </span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">whatLabels =</span> ?, <span class="co"># label lines as... </span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">rotation =</span> ? <span class="co"># rotations, +1 = 90degrees</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>        )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: handy functionality!
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Occasionally we might want to draw models before we even get the data. <strong>lavaan</strong> has some useful functionality where you can give it a model formula and ask it to “lavaanify” it into a model object that just hasn’t yet been fitted to anything.</p>
<p>For instance, by setting up a pretend model and “lavaanify-ing” it, we can then make a diagram!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>pretend_model <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="st">biscuits =~ digestive + oreo + custard_cream + bourbon + crackers</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="st">crisps =~ salt_vinegar + cheese_onion + prawn_cocktail + crackers</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lavaanify</span>(pretend_model) <span class="sc">|&gt;</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semPaths</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04_cfa_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="model-modifications" class="level1">
<h1>Model modifications</h1>
<div class="imp">
<p><strong>Confirmatory? Exploratory? “Explirmatory”? “Confloratory”?</strong><br>
<img src="images/meme_no_idea.jpg" class="img-fluid"></p>
</div>
<p>TODO</p>
<p>When a factor structure does not fit well, we can either start over and go back to doing EFA, deciding on an appropriate factor structure, on whether we should drop certain items, etc. The downside of this is that we essentially result in <em>another</em> version of the scale, and before we know it, we have 10 versions of the same measure floating around, in a perpetual state of scale-development. Alternatively, we can see if it is possible to minimally adjust our model based on areas of local misfit in order to see if our global fit improves. Note that this would still be in a sense <em>exploratory,</em> and we should be very clear when writing up about the process that we undertook. We should also avoid just shoving any parameter in that might make it fit better - we should let common sense and theoretical knowledge support any adjustments we make.</p>
<p>The <code>modindices()</code> function takes a fitted model object from <strong>lavaan</strong> and provides a table of all the possible additional parameters we <em>could</em> estimate.</p>
<p>The output is a table, which we can ask to be sorted according to the <code>mi</code> column using <code>sort = TRUE</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modindices</span>(myfittedmodel, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>      lhs op    rhs     mi    epc sepc.lv sepc.all sepc.nox
72  item6 ~~ item10 10.747  0.082   0.082    0.144    0.144
25 fact1  =~  item7  8.106  0.119   0.080    0.080    0.080
65  item5 ~~  item7  6.720  0.039   0.039    0.160    0.160
71  item6 ~~  item9  6.675 -0.065  -0.065   -0.115   -0.115
.   ...   .   ...    ...    ...     ...      ...      ...</code></pre>
<p>The columns show:</p>
<ul>
<li><code>lhs</code>,<code>op</code>,<code>rhs</code> : these three columns show the specific parameter, in lavaan syntax. So <code>fact1 =~ item7</code> is for the possible inclusion of <code>item7</code> being loaded on to the latent variable <code>fact1</code>. <code>item6 ~~ item10</code> is for the inclusion of a covariance between <code>item6</code> and <code>item10</code>, and so on.<br>
</li>
<li><code>mi</code> : “modification index” = the change in the model <span class="math inline">\(\chi^2\)</span> value <em>were we to include this parameter in the model</em><br>
</li>
<li><code>epc</code> : “expected parameter change” = the estimated value that the parameter <em>would take were it included in the model</em><br>
</li>
<li><code>sepc.lv</code>, <code>sepc.all</code>, <code>sepc.nox</code> : these provide the <code>epc</code> values but scaled to when a) the latent variables are standardised, b) all variables are standardised, and c) all except exogenous observed variables are standardised (not relevant for CFA)</li>
</ul>
<p>Often, the <code>sepc.all</code>is a useful column to look at, because it shows the proposed parameter estimate in a standardised metric. i.e.&nbsp;if the <code>op</code> is <code>~~</code>, then the <code>sepc.all</code> value is a correlation, and so we can consider anything &lt;.2/.3ish to be quite small. If <code>op</code> is <code>=~</code>, then the <code>sepc.all</code> value is a standardised factor loading, so values &gt;.3 or &gt;.4 are worth thinking about, and so on.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
model modifications are exploratory!!
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>We could simply keep adding suggested parameters to our model and we will eventually end up with a perfectly fitting model.</p>
<p>It’s very important to think critically here about <em>why</em> such modifications may be necessary.</p>
<ul>
<li>The initial model may have failed to capture the complexity of the underlying relationships among variables. For instance, suggested residual covariances, representing unexplained covariation among observed variables, may indicate misspecification in the initial model.</li>
<li>The structure of the construct is genuinely different in your population from the initial one in which the scale is developed (this could be a research question in and of itself - i.e.&nbsp;does the structure of “anxiety” differ as people age, or differ between cultures?)</li>
</ul>
<p>Modifications to a CFA model should be made judiciously, with careful consideration of theory as well as quantitative metrics. The goal is to develop a model that accurately represents the underlying structure of the data while maintaining theoretical coherence and generalizability.</p>
</div>
</div>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>or in logistic regression, “what is the likelihood of observing the outcome <span class="math inline">\(y\)</span> given our model parameters?”<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>I think therefore I am?<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© Copyright 2019-2025 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>